"use server";

import { createClient, createAdminClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import type { NonprofitUserRole } from "@/types/database";

export async function inviteTeamMember(
  nonprofitId: string,
  email: string,
  role: NonprofitUserRole
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();
  const adminSupabase = createAdminClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Not authenticated" };
  }

  // Verify user is an admin of this nonprofit
  const { data: currentUserMembership } = await supabase
    .from("nonprofit_users")
    .select("role")
    .eq("nonprofit_id", nonprofitId)
    .eq("user_id", user.id)
    .single();

  if (!currentUserMembership || currentUserMembership.role !== "admin") {
    return { success: false, error: "Only admins can invite team members" };
  }

  // Check if there's already a pending invitation for this email
  const { data: existingInvitation } = await supabase
    .from("nonprofit_invitations")
    .select("id")
    .eq("nonprofit_id", nonprofitId)
    .eq("email", email)
    .is("accepted_at", null)
    .gt("expires_at", new Date().toISOString())
    .single();

  if (existingInvitation) {
    return { success: false, error: "An invitation has already been sent to this email" };
  }

  // Check if this email is already a team member
  const { data: existingMember } = await adminSupabase
    .from("users")
    .select("id")
    .eq("email", email)
    .single();

  if (existingMember) {
    const { data: existingMembership } = await supabase
      .from("nonprofit_users")
      .select("id")
      .eq("nonprofit_id", nonprofitId)
      .eq("user_id", existingMember.id)
      .single();

    if (existingMembership) {
      return { success: false, error: "This person is already a team member" };
    }
  }

  // Create the invitation
  const { error: insertError } = await adminSupabase
    .from("nonprofit_invitations")
    .insert({
      nonprofit_id: nonprofitId,
      email,
      role,
      invited_by: user.id,
      // Token and expiration are auto-generated by database trigger
    });

  if (insertError) {
    console.error("Failed to create invitation:", insertError);
    return { success: false, error: "Failed to create invitation" };
  }

  // TODO: Send invitation email
  // await sendTeamInvitationEmail(email, nonprofitId, role);

  revalidatePath("/nonprofit/team");

  return { success: true };
}

export async function removeTeamMember(
  memberId: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();
  const adminSupabase = createAdminClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Not authenticated" };
  }

  // Get the member to be removed
  const { data: memberToRemove, error: fetchError } = await supabase
    .from("nonprofit_users")
    .select("nonprofit_id, user_id")
    .eq("id", memberId)
    .single();

  if (fetchError || !memberToRemove) {
    return { success: false, error: "Team member not found" };
  }

  // Verify current user is an admin of this nonprofit
  const { data: currentUserMembership } = await supabase
    .from("nonprofit_users")
    .select("role")
    .eq("nonprofit_id", memberToRemove.nonprofit_id)
    .eq("user_id", user.id)
    .single();

  if (!currentUserMembership || currentUserMembership.role !== "admin") {
    return { success: false, error: "Only admins can remove team members" };
  }

  // Can't remove yourself
  if (memberToRemove.user_id === user.id) {
    return { success: false, error: "You cannot remove yourself from the team" };
  }

  // Remove the team member
  const { error: deleteError } = await adminSupabase
    .from("nonprofit_users")
    .delete()
    .eq("id", memberId);

  if (deleteError) {
    console.error("Failed to remove team member:", deleteError);
    return { success: false, error: "Failed to remove team member" };
  }

  revalidatePath("/nonprofit/team");

  return { success: true };
}

export async function updateTeamMemberRole(
  memberId: string,
  newRole: NonprofitUserRole
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();
  const adminSupabase = createAdminClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Not authenticated" };
  }

  // Get the member to update
  const { data: memberToUpdate, error: fetchError } = await supabase
    .from("nonprofit_users")
    .select("nonprofit_id, user_id")
    .eq("id", memberId)
    .single();

  if (fetchError || !memberToUpdate) {
    return { success: false, error: "Team member not found" };
  }

  // Verify current user is an admin of this nonprofit
  const { data: currentUserMembership } = await supabase
    .from("nonprofit_users")
    .select("role")
    .eq("nonprofit_id", memberToUpdate.nonprofit_id)
    .eq("user_id", user.id)
    .single();

  if (!currentUserMembership || currentUserMembership.role !== "admin") {
    return { success: false, error: "Only admins can change roles" };
  }

  // Can't change your own role
  if (memberToUpdate.user_id === user.id) {
    return { success: false, error: "You cannot change your own role" };
  }

  // Update the role
  const { error: updateError } = await adminSupabase
    .from("nonprofit_users")
    .update({ role: newRole })
    .eq("id", memberId);

  if (updateError) {
    console.error("Failed to update role:", updateError);
    return { success: false, error: "Failed to update role" };
  }

  revalidatePath("/nonprofit/team");

  return { success: true };
}

export async function cancelInvitation(
  invitationId: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();
  const adminSupabase = createAdminClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Not authenticated" };
  }

  // Get the invitation
  const { data: invitation, error: fetchError } = await supabase
    .from("nonprofit_invitations")
    .select("nonprofit_id")
    .eq("id", invitationId)
    .single();

  if (fetchError || !invitation) {
    return { success: false, error: "Invitation not found" };
  }

  // Verify current user is an admin of this nonprofit
  const { data: currentUserMembership } = await supabase
    .from("nonprofit_users")
    .select("role")
    .eq("nonprofit_id", invitation.nonprofit_id)
    .eq("user_id", user.id)
    .single();

  if (!currentUserMembership || currentUserMembership.role !== "admin") {
    return { success: false, error: "Only admins can cancel invitations" };
  }

  // Delete the invitation
  const { error: deleteError } = await adminSupabase
    .from("nonprofit_invitations")
    .delete()
    .eq("id", invitationId);

  if (deleteError) {
    console.error("Failed to cancel invitation:", deleteError);
    return { success: false, error: "Failed to cancel invitation" };
  }

  revalidatePath("/nonprofit/team");

  return { success: true };
}
