"use server";

import { revalidatePath } from "next/cache";
import { createAdminClient } from "@/lib/supabase/server";
import { requireOwner } from "@/lib/auth/permissions";
import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";

// Initialize Resend for email sending
const resend = new Resend(process.env.RESEND_API_KEY);
const EMAIL_FROM = process.env.RESEND_FROM_EMAIL || "DonorX <onboarding@resend.dev>";

export async function approveNonprofit(nonprofitId: string) {
  // Use admin client to bypass RLS for admin operations
  const adminSupabase = createAdminClient();

  // First, get the nonprofit to check for contact email
  const { data: nonprofit, error: fetchError } = await adminSupabase
    .from("nonprofits")
    .select("id, name, contact_email")
    .eq("id", nonprofitId)
    .single();

  if (fetchError) {
    console.error("Fetch nonprofit error:", fetchError);
    return { error: fetchError.message };
  }

  // Update the nonprofit status
  const { error } = await adminSupabase
    .from("nonprofits")
    .update({ status: "approved", approved_at: new Date().toISOString() })
    .eq("id", nonprofitId);

  if (error) {
    console.error("Approve nonprofit error:", error);
    return { error: error.message };
  }

  // If nonprofit has a contact email, set up portal access
  if (nonprofit?.contact_email) {
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://donor-x.vercel.app";

    // First, check if there's already an existing user with this email
    const { data: existingUser } = await adminSupabase
      .from("users")
      .select("id")
      .eq("email", nonprofit.contact_email)
      .single();

    if (existingUser) {
      // User already exists - create nonprofit_user record directly
      const { error: linkError } = await adminSupabase
        .from("nonprofit_users")
        .insert({
          nonprofit_id: nonprofitId,
          user_id: existingUser.id,
          role: "admin",
        })
        .select()
        .single();

      if (linkError && !linkError.message.includes("duplicate")) {
        console.error("Failed to link user to nonprofit:", linkError);
      } else {
        // Send approval email with direct portal link
        try {
          await resend.emails.send({
            from: EMAIL_FROM,
            to: nonprofit.contact_email,
            subject: `Your nonprofit ${nonprofit.name} has been approved on DonorX!`,
            html: generateApprovalEmailHtml({
              nonprofitName: nonprofit.name,
              portalUrl: `${baseUrl}/nonprofit`,
            }),
            text: generateApprovalEmailText({
              nonprofitName: nonprofit.name,
              portalUrl: `${baseUrl}/nonprofit`,
            }),
          });
        } catch (emailError) {
          console.error("Failed to send approval email:", emailError);
        }
      }
    } else {
      // User doesn't exist - create invitation for them to register
      const { data: invitation, error: inviteError } = await adminSupabase
        .from("nonprofit_invitations")
        .insert({
          nonprofit_id: nonprofitId,
          email: nonprofit.contact_email,
          role: "admin",
          // Token is auto-generated by database trigger
          // Expiration is set to 7 days by default
        })
        .select("token")
        .single();

      if (inviteError) {
        console.error("Failed to create nonprofit invitation:", inviteError);
        // Don't fail the approval if invitation creation fails
        // The admin can manually invite later
      } else if (invitation?.token) {
        // Send invitation email
        const inviteUrl = `${baseUrl}/nonprofit/invite?token=${invitation.token}`;

        try {
          await resend.emails.send({
            from: EMAIL_FROM,
            to: nonprofit.contact_email,
            subject: `Your nonprofit ${nonprofit.name} has been approved on DonorX!`,
            html: generateNonprofitInvitationEmailHtml({
              nonprofitName: nonprofit.name,
              inviteUrl,
            }),
            text: generateNonprofitInvitationEmailText({
              nonprofitName: nonprofit.name,
              inviteUrl,
            }),
          });
        } catch (emailError) {
          console.error("Failed to send nonprofit invitation email:", emailError);
          // Don't fail the approval if email fails
        }
      }
    }
  }

  revalidatePath("/admin/nonprofits");
  revalidatePath("/admin");
  revalidatePath("/directory");
  return { success: true };
}

export async function rejectNonprofit(nonprofitId: string) {
  // Use admin client to bypass RLS for admin operations
  const adminSupabase = createAdminClient();

  const { error } = await adminSupabase
    .from("nonprofits")
    .update({ status: "rejected" })
    .eq("id", nonprofitId);

  if (error) {
    console.error("Reject nonprofit error:", error);
    return { error: error.message };
  }

  revalidatePath("/admin/nonprofits");
  revalidatePath("/admin");
  return { success: true };
}

export async function toggleFeatured(nonprofitId: string, featured: boolean) {
  // Note: is_featured column doesn't exist in DB yet
  // This is a placeholder for future feature
  console.log(`toggleFeatured called for ${nonprofitId}, featured: ${featured}`);

  revalidatePath("/admin/nonprofits");
  revalidatePath("/directory");
  return { success: true };
}

export async function deleteNonprofit(nonprofitId: string) {
  // Only owners can delete nonprofits
  const ownerCheck = await requireOwner();
  if ("error" in ownerCheck) {
    return { error: ownerCheck.error };
  }

  // Use admin client to bypass RLS for admin operations
  const adminSupabase = createAdminClient();

  // Check for allocations to this nonprofit and whether they're from simulated donations
  const { data: allocations } = await adminSupabase
    .from("allocations")
    .select(`
      id,
      donation_id,
      donation:donations(id, is_simulated)
    `)
    .eq("nonprofit_id", nonprofitId);

  if (allocations && allocations.length > 0) {
    // Check if any allocations are from real (non-simulated) donations
    // Supabase returns single relations as objects, but TypeScript thinks it's an array
    const hasRealDonations = allocations.some((alloc) => {
      const donation = alloc.donation as unknown as { id: string; is_simulated: boolean } | null;
      return donation && !donation.is_simulated;
    });

    if (hasRealDonations) {
      return { error: "Cannot delete nonprofit with real donations. Only nonprofits with simulated donations can be deleted." };
    }

    // All donations are simulated - delete them
    // First, get unique donation IDs
    const simulatedDonationIds = [...new Set(
      allocations
        .filter((alloc) => {
          const donation = alloc.donation as unknown as { id: string; is_simulated: boolean } | null;
          return donation?.is_simulated;
        })
        .map((alloc) => alloc.donation_id)
    )];

    if (simulatedDonationIds.length > 0) {
      // Delete allocations for these donations first (due to foreign key)
      const { error: allocDeleteError } = await adminSupabase
        .from("allocations")
        .delete()
        .in("donation_id", simulatedDonationIds);

      if (allocDeleteError) {
        console.error("Delete allocations error:", allocDeleteError);
        return { error: `Failed to delete simulated allocations: ${allocDeleteError.message}` };
      }

      // Delete the simulated donations
      const { error: donationDeleteError } = await adminSupabase
        .from("donations")
        .delete()
        .in("id", simulatedDonationIds);

      if (donationDeleteError) {
        console.error("Delete donations error:", donationDeleteError);
        return { error: `Failed to delete simulated donations: ${donationDeleteError.message}` };
      }
    }
  }

  // Now delete the nonprofit
  const { error } = await adminSupabase
    .from("nonprofits")
    .delete()
    .eq("id", nonprofitId);

  if (error) {
    console.error("Delete nonprofit error:", error);
    return { error: error.message };
  }

  revalidatePath("/admin/nonprofits");
  revalidatePath("/admin");
  revalidatePath("/directory");
  revalidatePath("/dashboard/history");
  revalidatePath("/dashboard/receipts");
  return { success: true };
}

export async function createNonprofit(formData: FormData) {
  // Use admin client to bypass RLS for admin operations
  const adminSupabase = createAdminClient();

  const name = formData.get("name") as string;
  const ein = formData.get("ein") as string;
  const description = formData.get("description") as string;
  const mission = formData.get("mission") as string;
  const website = formData.get("website") as string;
  const categoryId = formData.get("category_id") as string;
  const logoUrl = formData.get("logo_url") as string;

  if (!name) {
    return { error: "Name is required" };
  }

  const { error } = await adminSupabase.from("nonprofits").insert({
    name,
    ein,
    description: description || null,
    mission: mission || null,
    website: website || null,
    category_id: categoryId || null,
    logo_url: logoUrl || null,
    status: "approved", // Admin-added nonprofits are auto-approved
    approved_at: new Date().toISOString(),
  });

  if (error) {
    console.error("Create nonprofit error:", error);
    return { error: error.message };
  }

  revalidatePath("/admin/nonprofits");
  revalidatePath("/admin");
  revalidatePath("/directory");
  return { success: true };
}

export async function updateNonprofit(nonprofitId: string, formData: FormData) {
  // Use admin client to bypass RLS for admin operations
  const adminSupabase = createAdminClient();

  const name = formData.get("name") as string;
  const ein = formData.get("ein") as string;
  const description = formData.get("description") as string;
  const mission = formData.get("mission") as string;
  const website = formData.get("website") as string;
  const categoryId = formData.get("category_id") as string;
  const logoUrl = formData.get("logo_url") as string;

  if (!name) {
    return { error: "Name is required" };
  }

  const { error } = await adminSupabase
    .from("nonprofits")
    .update({
      name,
      ein,
      description: description || null,
      mission: mission || null,
      website: website || null,
      category_id: categoryId || null,
      logo_url: logoUrl || null,
    })
    .eq("id", nonprofitId);

  if (error) {
    console.error("Update nonprofit error:", error);
    return { error: error.message };
  }

  revalidatePath("/admin/nonprofits");
  revalidatePath("/directory");
  revalidatePath(`/directory/${nonprofitId}`);
  return { success: true };
}

export interface ExtractedNonprofitInfo {
  name?: string;
  logoUrl?: string;
  description?: string;
  mission?: string;
  suggestedCategory?: string;
  error?: string;
}

async function fetchPageContent(url: string): Promise<string | null> {
  try {
    const response = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      },
    });
    if (response.ok) {
      return await response.text();
    }
  } catch {
    // Ignore fetch errors for secondary pages
  }
  return null;
}

function extractBaseUrl(url: string): string {
  try {
    const parsed = new URL(url);
    return `${parsed.protocol}//${parsed.host}`;
  } catch {
    return url;
  }
}

export async function extractNonprofitInfo(websiteUrl: string): Promise<ExtractedNonprofitInfo> {
  if (!websiteUrl) {
    return { error: "Website URL is required" };
  }

  try {
    const baseUrl = extractBaseUrl(websiteUrl);

    // Fetch the main page and common about/mission pages in parallel
    const pagesToTry = [
      websiteUrl,
      `${baseUrl}/about`,
      `${baseUrl}/about-us`,
      `${baseUrl}/mission`,
      `${baseUrl}/who-we-are`,
      `${baseUrl}/our-mission`,
      `${baseUrl}/what-we-do`,
    ];

    const pagePromises = pagesToTry.map(fetchPageContent);
    const pageResults = await Promise.all(pagePromises);

    // Combine all successfully fetched content
    const allContent: string[] = [];
    pageResults.forEach((content, index) => {
      if (content) {
        allContent.push(`\n--- PAGE: ${pagesToTry[index]} ---\n${content.slice(0, 30000)}`);
      }
    });

    if (allContent.length === 0) {
      return { error: "Failed to fetch any pages from the website" };
    }

    // Combine content, limiting total size
    const combinedHtml = allContent.join("\n").slice(0, 100000);

    // Use Claude to extract nonprofit information
    const anthropic = new Anthropic();

    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1000,
      messages: [
        {
          role: "user",
          content: `You are extracting nonprofit information from website HTML. The content may come from multiple pages of the same site.

IMPORTANT: Many modern websites (Wix, Squarespace, etc.) render content via JavaScript, so the main body may be empty. Look carefully in these locations:

1. **META TAGS** (highest priority for JS-rendered sites):
   - og:title, og:description, og:image
   - twitter:title, twitter:description, twitter:image
   - meta name="description"
   - meta name="keywords"

2. **STRUCTURED DATA**:
   - JSON-LD scripts (type: "Organization", "NonProfit", "NGO")
   - Schema.org markup

3. **PAGE CONTENT** (if available):
   - Header/nav text, navigation menu items
   - Hero sections
   - About sections
   - Any visible text content

4. **INFER FROM CONTEXT**:
   - Domain name often hints at the organization's focus
   - Image filenames and alt text
   - URL paths (e.g., /donate, /events, /programs)

Extract (ALWAYS provide values for ALL fields - infer if not explicitly stated):
1. **Organization Name**: Look in og:title, page title, JSON-LD, or prominent headers
2. **Logo URL**: Look in og:image, twitter:image, JSON-LD logo, link rel="icon", apple-touch-icon. Convert relative URLs to absolute using base: ${websiteUrl}
3. **Short Description**: 1-2 sentences about what they do. Use og:description, meta description, or INFER from organization name and any context clues
4. **Mission Statement**: Their mission/purpose. If not explicitly found, GENERATE a plausible mission statement based on the organization name, description, and category (e.g., "812 MX Ministry exists to share the love of Christ through the sport of motocross, providing a welcoming community for riders and families.")
5. **Category**: ALWAYS select EXACTLY ONE from this list (use exact spelling): Animal Welfare, Arts & Culture, Disaster Relief, Education, Environment, Healthcare, Housing, Human Rights, Hunger Relief, Military Veterans, Religious, Sports Ministry, Youth Development. Infer from organization name and context:
   - Military/veteran organizations → "Military Veterans"
   - Food banks, hunger relief → "Hunger Relief"
   - Medical/health → "Healthcare"
   - Animal rescue/shelters → "Animal Welfare"
   - Faith-based sports ministries → "Sports Ministry"
   - Churches, missions, faith-based charities → "Religious"
   - Civil rights, advocacy → "Human Rights"
   - Homeless services, affordable housing → "Housing"

CRITICAL RULES:
- NEVER return null for category - always select from the exact list above
- NEVER return null for mission - generate one if not found
- The category MUST be one of the 13 exact options listed above (case-sensitive)
- Be creative and use all context clues available

Respond ONLY with valid JSON (no markdown, no explanation):
{"name":"...","logoUrl":"...","description":"...","mission":"...","suggestedCategory":"..."}

HTML CONTENT:
${combinedHtml}`
        }
      ]
    });

    const responseText = message.content[0].type === "text" ? message.content[0].text.trim() : "";

    try {
      const parsed = JSON.parse(responseText);

      if (parsed.error) {
        return { error: parsed.error };
      }

      return {
        name: parsed.name || undefined,
        logoUrl: parsed.logoUrl || undefined,
        description: parsed.description || undefined,
        mission: parsed.mission || undefined,
        suggestedCategory: parsed.suggestedCategory || undefined,
      };
    } catch {
      return { error: "Failed to parse AI response" };
    }
  } catch (error) {
    console.error("Nonprofit info extraction error:", error);

    // Check for API credit/billing errors
    const errorMessage = error instanceof Error ? error.message : String(error);
    if (errorMessage.includes("credit balance") || errorMessage.includes("billing") || errorMessage.includes("invalid_request_error")) {
      return { error: "AI extraction temporarily unavailable. Please enter details manually." };
    }

    return { error: "Failed to extract nonprofit info. Please enter details manually." };
  }
}

export async function uploadNonprofitLogo(formData: FormData): Promise<{ logoUrl?: string; error?: string }> {
  const file = formData.get("logo") as File;

  if (!file || file.size === 0) {
    return { error: "No file provided" };
  }

  // Validate file type
  const allowedTypes = ["image/jpeg", "image/png", "image/gif", "image/webp", "image/svg+xml"];
  if (!allowedTypes.includes(file.type)) {
    return { error: "Invalid file type. Please upload a JPG, PNG, GIF, WebP, or SVG image." };
  }

  // Validate file size (max 2MB)
  const maxSize = 2 * 1024 * 1024;
  if (file.size > maxSize) {
    return { error: "File too large. Maximum size is 2MB." };
  }

  try {
    const adminSupabase = createAdminClient();

    // Generate unique filename
    const fileExt = file.name.split(".").pop()?.toLowerCase() || "png";
    const fileName = `${Date.now()}-${Math.random().toString(36).substring(2, 9)}.${fileExt}`;
    const filePath = `nonprofit-logos/${fileName}`;

    // Convert File to ArrayBuffer then to Uint8Array for Supabase
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);

    // Upload to Supabase Storage
    const { error: uploadError } = await adminSupabase.storage
      .from("public-assets")
      .upload(filePath, uint8Array, {
        contentType: file.type,
        cacheControl: "3600",
        upsert: false,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return { error: `Upload failed: ${uploadError.message}` };
    }

    // Get public URL
    const { data: { publicUrl } } = adminSupabase.storage
      .from("public-assets")
      .getPublicUrl(filePath);

    return { logoUrl: publicUrl };
  } catch (error) {
    console.error("Logo upload error:", error);
    return { error: error instanceof Error ? error.message : "Failed to upload logo" };
  }
}

export async function detectLogoUrl(websiteUrl: string): Promise<{ logoUrl?: string; error?: string }> {
  if (!websiteUrl) {
    return { error: "Website URL is required" };
  }

  try {
    // Fetch the website HTML
    const response = await fetch(websiteUrl, {
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; DonorX/1.0)",
      },
    });

    if (!response.ok) {
      return { error: `Failed to fetch website: ${response.status}` };
    }

    const html = await response.text();

    // Truncate HTML to avoid token limits (keep first 50KB)
    const truncatedHtml = html.slice(0, 50000);

    // Use Claude to extract the logo URL
    const anthropic = new Anthropic();

    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 500,
      messages: [
        {
          role: "user",
          content: `Analyze this HTML and find the organization's logo URL. Look for:
1. Open Graph image (og:image meta tag)
2. Twitter card image
3. Favicon or apple-touch-icon
4. Logo in header/nav (img tags with "logo" in class, id, alt, or src)
5. Site icon link tags

Return ONLY the full absolute URL of the best logo image found. If the URL is relative, convert it to absolute using the base URL: ${websiteUrl}

If no suitable logo is found, respond with just "NOT_FOUND".

HTML:
${truncatedHtml}`
        }
      ]
    });

    const responseText = message.content[0].type === "text" ? message.content[0].text.trim() : "";

    if (responseText === "NOT_FOUND" || !responseText) {
      return { error: "No logo found on the website" };
    }

    // Basic URL validation
    try {
      new URL(responseText);
      return { logoUrl: responseText };
    } catch {
      return { error: "Invalid logo URL extracted" };
    }
  } catch (error) {
    console.error("Logo detection error:", error);

    // Check for API credit/billing errors
    const errorMessage = error instanceof Error ? error.message : String(error);
    if (errorMessage.includes("credit balance") || errorMessage.includes("billing") || errorMessage.includes("invalid_request_error")) {
      return { error: "Logo detection temporarily unavailable. Please enter URL manually." };
    }

    return { error: "Failed to detect logo. Please enter URL manually." };
  }
}

// Email template generators for nonprofit invitations
interface NonprofitEmailTemplateParams {
  nonprofitName: string;
  inviteUrl: string;
}

function generateNonprofitInvitationEmailHtml(params: NonprofitEmailTemplateParams): string {
  const { nonprofitName, inviteUrl } = params;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Nonprofit Has Been Approved!</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #334155; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 32px; border-radius: 12px 12px 0 0; text-align: center;">
    <h1 style="color: white; margin: 0; font-size: 24px;">
      Congratulations! 🎉
    </h1>
    <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 16px;">
      Your nonprofit has been approved
    </p>
  </div>

  <div style="background: #ffffff; padding: 32px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
    <p style="font-size: 16px; margin-bottom: 24px;">
      Great news! <strong>${nonprofitName}</strong> has been approved on DonorX and is now live in our nonprofit directory.
    </p>

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      You can now access your Nonprofit Portal to:
    </p>

    <ul style="font-size: 14px; color: #64748b; margin-bottom: 24px; padding-left: 20px;">
      <li>Update your organization's profile and logo</li>
      <li>Set fundraising goals</li>
      <li>Create embeddable donation widgets for your website</li>
      <li>View donation analytics</li>
      <li>Manage your team members</li>
    </ul>

    <div style="text-align: center; margin: 32px 0;">
      <a href="${inviteUrl}" style="display: inline-block; background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px;">
        Access Your Nonprofit Portal
      </a>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #86efac; border-radius: 8px; padding: 16px; margin-top: 24px;">
      <p style="margin: 0; font-size: 14px; color: #166534;">
        <strong>What's next?</strong> Click the button above to set up your account and start customizing your nonprofit's presence on DonorX.
      </p>
    </div>

    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">

    <div style="font-size: 12px; color: #94a3b8;">
      <p style="margin-bottom: 8px;">
        This invitation link expires in 7 days. If you need a new link, please contact us.
      </p>
      <p style="margin: 0;">
        Button not working? Copy and paste this link into your browser:<br>
        <span style="word-break: break-all; color: #64748b;">${inviteUrl}</span>
      </p>
    </div>
  </div>

  <div style="text-align: center; padding: 20px; font-size: 12px; color: #94a3b8;">
    <p style="margin: 0;">© ${new Date().getFullYear()} DonorX. All rights reserved.</p>
  </div>
</body>
</html>
  `.trim();
}

function generateNonprofitInvitationEmailText(params: NonprofitEmailTemplateParams): string {
  const { nonprofitName, inviteUrl } = params;

  return `
Congratulations! Your Nonprofit Has Been Approved!

Great news! ${nonprofitName} has been approved on DonorX and is now live in our nonprofit directory.

You can now access your Nonprofit Portal to:
- Update your organization's profile and logo
- Set fundraising goals
- Create embeddable donation widgets for your website
- View donation analytics
- Manage your team members

Access your portal here:
${inviteUrl}

What's next? Click the link above to set up your account and start customizing your nonprofit's presence on DonorX.

---

This invitation link expires in 7 days. If you need a new link, please contact us.

© ${new Date().getFullYear()} DonorX. All rights reserved.
  `.trim();
}

// Email templates for existing users (direct approval, no invitation needed)
interface ApprovalEmailParams {
  nonprofitName: string;
  portalUrl: string;
}

function generateApprovalEmailHtml(params: ApprovalEmailParams): string {
  const { nonprofitName, portalUrl } = params;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Nonprofit Has Been Approved!</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #334155; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 32px; border-radius: 12px 12px 0 0; text-align: center;">
    <h1 style="color: white; margin: 0; font-size: 24px;">
      Congratulations! 🎉
    </h1>
    <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 16px;">
      Your nonprofit has been approved
    </p>
  </div>

  <div style="background: #ffffff; padding: 32px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
    <p style="font-size: 16px; margin-bottom: 24px;">
      Great news! <strong>${nonprofitName}</strong> has been approved on DonorX and is now live in our nonprofit directory.
    </p>

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      Your account has been automatically linked as an admin. You can now access your Nonprofit Portal to:
    </p>

    <ul style="font-size: 14px; color: #64748b; margin-bottom: 24px; padding-left: 20px;">
      <li>Update your organization's profile and logo</li>
      <li>Set fundraising goals</li>
      <li>Create embeddable donation widgets for your website</li>
      <li>View donation analytics</li>
      <li>Manage your team members</li>
    </ul>

    <div style="text-align: center; margin: 32px 0;">
      <a href="${portalUrl}" style="display: inline-block; background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px;">
        Go to Your Nonprofit Portal
      </a>
    </div>

    <div style="background: #f0fdf4; border: 1px solid #86efac; border-radius: 8px; padding: 16px; margin-top: 24px;">
      <p style="margin: 0; font-size: 14px; color: #166534;">
        <strong>Ready to go!</strong> Just log in with your existing account and you'll see the Nonprofit Portal option in your menu.
      </p>
    </div>

    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">

    <div style="font-size: 12px; color: #94a3b8;">
      <p style="margin: 0;">
        Button not working? Copy and paste this link into your browser:<br>
        <span style="word-break: break-all; color: #64748b;">${portalUrl}</span>
      </p>
    </div>
  </div>

  <div style="text-align: center; padding: 20px; font-size: 12px; color: #94a3b8;">
    <p style="margin: 0;">© ${new Date().getFullYear()} DonorX. All rights reserved.</p>
  </div>
</body>
</html>
  `.trim();
}

function generateApprovalEmailText(params: ApprovalEmailParams): string {
  const { nonprofitName, portalUrl } = params;

  return `
Congratulations! Your Nonprofit Has Been Approved!

Great news! ${nonprofitName} has been approved on DonorX and is now live in our nonprofit directory.

Your account has been automatically linked as an admin. You can now access your Nonprofit Portal to:
- Update your organization's profile and logo
- Set fundraising goals
- Create embeddable donation widgets for your website
- View donation analytics
- Manage your team members

Go to your portal:
${portalUrl}

Ready to go! Just log in with your existing account and you'll see the Nonprofit Portal option in your menu.

© ${new Date().getFullYear()} DonorX. All rights reserved.
  `.trim();
}
