"use server";

import { createAdminClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

export interface CreateWidgetData {
  name: string;
  nonprofit_id: string;
  primary_color?: string;
  button_text?: string;
  show_cover_fees?: boolean;
  show_anonymous?: boolean;
  show_dedications?: boolean;
  allow_custom_amount?: boolean;
  min_amount_cents?: number;
  preset_amounts?: number[];
}

export async function createWidget(
  data: CreateWidgetData
): Promise<{ success: boolean; error?: string; widgetId?: string }> {
  const adminSupabase = createAdminClient();

  if (!data.name || !data.nonprofit_id) {
    return { success: false, error: "Name and nonprofit are required" };
  }

  const { data: widget, error } = await adminSupabase
    .from("widget_tokens")
    .insert({
      name: data.name,
      nonprofit_id: data.nonprofit_id,
      primary_color: data.primary_color || "#059669",
      button_text: data.button_text || "Donate Now",
      show_cover_fees: data.show_cover_fees ?? true,
      show_anonymous: data.show_anonymous ?? true,
      show_dedications: data.show_dedications ?? false,
      allow_custom_amount: data.allow_custom_amount ?? true,
      min_amount_cents: data.min_amount_cents || 500,
      preset_amounts: data.preset_amounts || [2500, 5000, 10000, 25000],
      // Token is auto-generated by database trigger
    })
    .select("id")
    .single();

  if (error) {
    console.error("Failed to create widget:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/admin/widgets");

  return { success: true, widgetId: widget.id };
}

export async function updateWidget(
  widgetId: string,
  data: Partial<CreateWidgetData> & { is_active?: boolean }
): Promise<{ success: boolean; error?: string }> {
  const adminSupabase = createAdminClient();

  const { error } = await adminSupabase
    .from("widget_tokens")
    .update({
      ...(data.name && { name: data.name }),
      ...(data.primary_color && { primary_color: data.primary_color }),
      ...(data.button_text && { button_text: data.button_text }),
      ...(typeof data.show_cover_fees === "boolean" && {
        show_cover_fees: data.show_cover_fees,
      }),
      ...(typeof data.show_anonymous === "boolean" && {
        show_anonymous: data.show_anonymous,
      }),
      ...(typeof data.show_dedications === "boolean" && {
        show_dedications: data.show_dedications,
      }),
      ...(typeof data.allow_custom_amount === "boolean" && {
        allow_custom_amount: data.allow_custom_amount,
      }),
      ...(data.min_amount_cents && { min_amount_cents: data.min_amount_cents }),
      ...(data.preset_amounts && { preset_amounts: data.preset_amounts }),
      ...(typeof data.is_active === "boolean" && { is_active: data.is_active }),
    })
    .eq("id", widgetId);

  if (error) {
    console.error("Failed to update widget:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/admin/widgets");
  revalidatePath(`/admin/widgets/${widgetId}`);

  return { success: true };
}

export async function deleteWidget(
  widgetId: string
): Promise<{ success: boolean; error?: string }> {
  const adminSupabase = createAdminClient();

  const { error } = await adminSupabase
    .from("widget_tokens")
    .delete()
    .eq("id", widgetId);

  if (error) {
    console.error("Failed to delete widget:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/admin/widgets");

  return { success: true };
}

export async function toggleWidgetActive(
  widgetId: string,
  isActive: boolean
): Promise<{ success: boolean; error?: string }> {
  const adminSupabase = createAdminClient();

  const { error } = await adminSupabase
    .from("widget_tokens")
    .update({ is_active: isActive })
    .eq("id", widgetId);

  if (error) {
    console.error("Failed to toggle widget:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/admin/widgets");
  revalidatePath(`/admin/widgets/${widgetId}`);

  return { success: true };
}
